<?php
session_start();
require_once __DIR__ . '/../../config.php';
require_once __DIR__ . '/../../includes/db.php';

// Admin authentication check
if (!isset($_SESSION['user_id']) || !isset($_SESSION['is_admin']) || !$_SESSION['is_admin']) {
    $_SESSION['admin_error'] = "Access denied.";
    header("Location: " . SITE_URL . "login/");
    exit;
}

$db = db_connect();
$error_message = '';
$success_message = '';

// Handle form submission before any HTML output
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $user_id = $_POST['user_id'] ?? null;
    $referral_code = $_POST['referral_code'] ?? uniqid('ref_');

    if (empty($user_id) || empty($referral_code)) {
        $error_message = "Please select a user and provide a referral code.";
    } else {
        // Check if referral code is unique
        $sql_check = "SELECT id FROM affiliates WHERE referral_code = ?";
        $stmt_check = $db->prepare($sql_check);
        $stmt_check->execute([$referral_code]);
        if ($stmt_check->fetch()) {
            $error_message = "This referral code is already in use.";
        } else {
            $sql_insert = "INSERT INTO affiliates (user_id, referral_code, status) VALUES (?, ?, 'active')";
            $stmt_insert = $db->prepare($sql_insert);
            if ($stmt_insert->execute([$user_id, $referral_code])) {
                $_SESSION['success_message'] = "Affiliate added successfully.";
                header("Location: " . SITE_URL . "admin/affiliates/");
                exit;
            } else {
                $error_message = "Failed to add affiliate. Please try again.";
            }
        }
    }
}


$page_title = "Add New Affiliate";
$breadcrumbs = [
    ['name' => 'Affiliates', 'url' => SITE_URL . 'admin/affiliates/'],
    ['name' => 'Add New Affiliate']
];
require_once __DIR__ . '/../includes/header.php';

// Fetch users who are not already affiliates
$sql_users = "SELECT id, name, email FROM users WHERE id NOT IN (SELECT user_id FROM affiliates)";
$stmt_users = $db->prepare($sql_users);
$stmt_users->execute();
$users = $stmt_users->fetchAll(PDO::FETCH_ASSOC);

?>

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2"><?php echo $page_title; ?></h1>
</div>

<?php if ($error_message): ?>
    <div class="alert alert-danger"><?php echo htmlspecialchars($error_message); ?></div>
<?php endif; ?>

<form action="" method="POST">
    <div class="mb-3">
        <label for="user_id" class="form-label">Select User</label>
        <select class="form-control" id="user_id" name="user_id" required>
            <option value="">-- Select a User --</option>
            <?php foreach ($users as $user): ?>
                <option value="<?php echo $user['id']; ?>"><?php echo htmlspecialchars($user['name']); ?> (<?php echo htmlspecialchars($user['email']); ?>)</option>
            <?php endforeach; ?>
        </select>
    </div>
    <div class="mb-3">
        <label for="referral_code" class="form-label">Referral Code</label>
        <input type="text" class="form-control" id="referral_code" name="referral_code" value="<?php echo uniqid('ref_'); ?>" required>
        <small class="form-text text-muted">A unique referral code will be generated by default.</small>
    </div>
    <button type="submit" class="btn btn-primary">Add Affiliate</button>
</form>

<?php
require_once __DIR__ . '/../includes/footer.php';
?>