<?php
session_start();
require_once __DIR__ . '/../../config.php';
require_once __DIR__ . '/../../includes/db.php';

// Admin authentication check
if (!isset($_SESSION['user_id']) || !isset($_SESSION['is_admin']) || !$_SESSION['is_admin']) {
    $_SESSION['admin_error'] = "Access denied.";
    header("Location: " . SITE_URL . "login/");
    exit;
}

$conn = new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME);
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

$error_message = '';
$success_message = '';

// Handle form submission before any HTML output
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $user_id = $_POST['user_id'] ?? null;
    $referral_code = $_POST['referral_code'] ?? uniqid('ref_');

    if (empty($user_id) || empty($referral_code)) {
        $error_message = "Please select a user and provide a referral code.";
    } else {
        // Check if referral code is unique
        $stmt_check = $conn->prepare("SELECT id FROM affiliates WHERE referral_code = ?");
        $stmt_check->bind_param("s", $referral_code);
        $stmt_check->execute();
        $result_check = $stmt_check->get_result();
        if ($result_check->num_rows > 0) {
            $error_message = "This referral code is already in use.";
        } else {
            $stmt_insert = $conn->prepare("INSERT INTO affiliates (user_id, referral_code, status) VALUES (?, ?, 'active')");
            $stmt_insert->bind_param("is", $user_id, $referral_code);
            if ($stmt_insert->execute()) {
                $_SESSION['success_message'] = "Affiliate added successfully.";
                header("Location: " . SITE_URL . "admin/affiliates/");
                exit;
            } else {
                $error_message = "Failed to add affiliate. Please try again.";
            }
        }
    }
}


$page_title = "Add New Affiliate";
$breadcrumbs = [
    ['name' => 'Affiliates', 'url' => SITE_URL . 'admin/affiliates/'],
    ['name' => 'Add New Affiliate']
];
require_once __DIR__ . '/../includes/header.php';

// Fetch users who are not already affiliates
$sql_users = "SELECT id, name, email FROM users WHERE id NOT IN (SELECT user_id FROM affiliates)";
$result = $conn->query($sql_users);
$users = [];
if ($result) {
    while ($row = $result->fetch_assoc()) {
        $users[] = $row;
    }
}

?>

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2"><?php echo $page_title; ?></h1>
</div>

<?php if ($error_message): ?>
    <div class="alert alert-danger"><?php echo htmlspecialchars($error_message); ?></div>
<?php endif; ?>

<form action="" method="POST">
    <div class="mb-3">
        <label for="user_id" class="form-label">Select User</label>
        <select class="form-control" id="user_id" name="user_id" required>
            <option value="">-- Select a User --</option>
            <?php foreach ($users as $user): ?>
                <option value="<?php echo $user['id']; ?>"><?php echo htmlspecialchars($user['name']); ?> (<?php echo htmlspecialchars($user['email']); ?>)</option>
            <?php endforeach; ?>
        </select>
    </div>
    <div class="mb-3">
        <label for="referral_code" class="form-label">Referral Code</label>
        <input type="text" class="form-control" id="referral_code" name="referral_code" value="<?php echo uniqid('ref_'); ?>" required>
        <small class="form-text text-muted">A unique referral code will be generated by default.</small>
    </div>
    <button type="submit" class="btn btn-primary">Add Affiliate</button>
</form>

<?php
require_once __DIR__ . '/../includes/footer.php';
?>